### PR TITLE
Feature/CVSB-19222

### PR DESCRIPTION
**Pull request by PaulBenn-BJSS**
Fix queue name + add debug logs

### CODE REVIEW

**Review by SanjeetJ-TA — COMMENTED** [review]
src/functions/edhMarshaller.ts - i am worried that this may break the dispatcher as it may rely  on the event type being present

**Comment by PaulBenn-BJSS** [comment]
> src/functions/edhMarshaller.ts - i am worried that this may break the dispatcher as it may rely on the event type being present

Addressed: https://github.com/dvsa/cvs-tsk-edh-marshaller/pull/13/commits/173650526f2c155066f67c0851149b86572c889b

**Review by SanjeetJ-TA — APPROVED** [review]
Happy to approve

**Review by bristol-mike-jones — APPROVED** [review]
LGTM

**Pull request merged**
